name: ci
on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      # Prepare

      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Validate

      - run: make build

      - run: make test

      # Push

      - if: github.ref == 'refs/heads/main'
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: github.ref == 'refs/heads/main'
        name: Push image
        run: make push
